config/routes.rb
Rails.application.routes.draw do
  resources :twitterfeeds

   root 'twitterfeeds#index'

end

app/models/twitterfeed.rb
require 'twitter'
class Twitterfeed < ActiveRecord::Base



   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #before_filter :load_tweets

  #def load_tweets
     #  @tweets = user_timeline(2)# For this demonstration lets keep the tweets limited to the first 5 available.
 # end
end

app/controllers/twitterfeeds_controller.rb
class TwitterfeedsController < ApplicationController
  before_action :set_twitterfeed, only: [:show, :edit, :update, :destroy]


  # GET /twitterfeeds
  # GET /twitterfeeds.json
  def index
    @tweets = user_timeline(5)#@twitter_feed  = Twitter.user_timeline("SammyKhaleel").first.text
  end
  def user_timeline(qt)
    @@client.user_timeline(count: qt)
  end
  # GET /twitterfeeds/1
  # GET /twitterfeeds/1.json
  def show
  end

  # GET /twitterfeeds/new
  def new
    @twitterfeed = Twitterfeed.new
  end

  # GET /twitterfeeds/1/edit
  def edit
  end

  # POST /twitterfeeds
  # POST /twitterfeeds.json
  def create
    @twitterfeed = Twitterfeed.new(twitterfeed_params)

    respond_to do |format|
      if @twitterfeed.save
        format.html { redirect_to @twitterfeed, notice: 'Twitterfeed was successfully created.' }
        format.json { render :show, status: :created, location: @twitterfeed }
      else
        format.html { render :new }
        format.json { render json: @twitterfeed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /twitterfeeds/1
  # PATCH/PUT /twitterfeeds/1.json
  def update
    respond_to do |format|
      if @twitterfeed.update(twitterfeed_params)
        format.html { redirect_to @twitterfeed, notice: 'Twitterfeed was successfully updated.' }
        format.json { render :show, status: :ok, location: @twitterfeed }
      else
        format.html { render :edit }
        format.json { render json: @twitterfeed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twitterfeeds/1
  # DELETE /twitterfeeds/1.json
  def destroy
    @twitterfeed.destroy
    respond_to do |format|
      format.html { redirect_to twitterfeeds_url, notice: 'Twitterfeed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_twitterfeed
      @twitterfeed = Twitterfeed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def twitterfeed_params
      params[:twitterfeed]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/twitterfeeds_helper.rb
module TwitterfeedsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/twitterfeeds/_form.html.erb
<%= form_for(@twitterfeed) do |f| %>
  <% if @twitterfeed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@twitterfeed.errors.count, "error") %> prohibited this twitterfeed from being saved:</h2>

      <ul>
      <% @twitterfeed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/twitterfeeds/edit.html.erb
<h1>Editing twitterfeed</h1>

<%= render 'form' %>

<%= link_to 'Show', @twitterfeed %> |
<%= link_to 'Back', twitterfeeds_path %>

app/views/twitterfeeds/index.html.erb
hello world

<section id="tweets">
  <ul>
    <% @tweets.each do |tweet| %>
      <li><%= link_to tweet.text, "https://www.twitter.com/#{tweet.user.screen_name}" %></li>
      <%end%>
  </ul>

</section>

app/views/twitterfeeds/new.html.erb
<h1>New twitterfeed</h1>

<%= render 'form' %>

<%= link_to 'Back', twitterfeeds_path %>

app/views/twitterfeeds/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_twitterfeed_path(@twitterfeed) %> |
<%= link_to 'Back', twitterfeeds_path %>